### ISSUE TITLE
Error Latte/Compiler

### ISSUE THREAD

**Issue by JBurdik** [nette-examples/flat-file-blog#1]
Class "Latte\Compiler" not found

how to get rid of this error?

**Comment by delacry** [comment]
Hi @JBurdik, it should be fixed, you can try it now, because this project was using dev versions of packages, since when it was created there wasn't stable PHP 8 packages. But there is currently also little problem at https://github.com/nette/application/blob/bc5fcec214725cf339e506cf3ceec7ca26aa38f3/src/Bridges/ApplicationDI/LatteExtension.php#L106, but I contacted @dg and it should be fixed soon, if you want to try it, just edit that condition to
```php
if ($all || (isset($template->control) && $template->control instanceof Nette\Application\UI\Presenter)) {
```
